package it.services.instantpayment.utils

object ApiKeys {
    const val BASE_URL="https://instantpayment.co.in/api/"
    const val LOGIN_KEY="Login001"
    const val OPERATOR_KEY="GetOperator001"
    const val BBPS_OPERATOR_KEY="GetbbpsOperator001"
    const val BALANCE_KEY="Balance001"
    const val Recharge_KEY="Recharge001"
    const val BBPS_FETCH_KEY="Billfetch001"
    const val BBPS_PAY_KEY="Billpayment001"
    const val SENDER_VERIFY_KEY="CheckSender001"
    const val SENDER_VERIFY_UPI_KEY="UPICheckSender001"
    const val ADD_SENDER_KEY="SenderReg001"
    const val ADD_SENDER_UPI_KEY="UPISenderReg001"
    const val VALIDATE_SENDER_KEY="SenderValidate001"
    const val VALIDATE_SENDER_UPI_KEY="UPISenderValidate001"
    const val BENE_LIST_KEY="BeneList001"
    const val BENE_LIST_UPI_KEY="UPIBeneList001"
    const val BANK_LIST_KEY="GetBank001"
    const val ADD_BENE_KEY="BeneReg001"
    const val ADD_BENE_UPI_KEY="UPIBeneReg001"
    const val VERIFY_BENE_UPI_KEY="AccountVarify001"
    const val PAY_BENE_KEY="MoneyTransfer001"
    const val PAY_BENE_UPI_KEY="UPIMoneyTransfer001"
    const val REPORTS_KEY="Report001"
    const val RECEIPT_KEY="Receipt001"
    const val INITIATE_PAYMENT_KEY="PaymentIniiate001"
    const val UPDATE_PAYMENT_KEY="UpdateStatus001"
}